// Code generated by protoc-gen-go.
// source: quete.proto
// DO NOT EDIT!

/*
Package beans is a generated protocol buffer package.

It is generated from these files:
	quete.proto
	sendMail.proto

It has these top-level messages:
	Quete
	SendMail
*/
package beans

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Quete struct {
	UseService string `protobuf:"bytes,1,opt,name=UseService"   json:"UseService"`
	UseParams  string `protobuf:"bytes,2,opt,name=UseParams"    json:"UseParams"`
}

func (m *Quete) Reset()                    { *m = Quete{} }
func (m *Quete) String() string            { return proto.CompactTextString(m) }
func (*Quete) ProtoMessage()               {}
func (*Quete) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Quete) GetUseService() string {
	if m != nil {
		return m.UseService
	}
	return ""
}

func (m *Quete) GetUseParams() string {
	if m != nil {
		return m.UseParams
	}
	return ""
}

func init() {
	proto.RegisterType((*Quete)(nil), "beans.Quete")
}

func init() { proto.RegisterFile("quete.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 98 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0x2c, 0x4d, 0x2d,
	0x49, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4d, 0x4a, 0x4d, 0xcc, 0x2b, 0x56, 0x72,
	0xe5, 0x62, 0x0d, 0x04, 0x89, 0x0a, 0xc9, 0x71, 0x71, 0x85, 0x16, 0xa7, 0x06, 0xa7, 0x16, 0x95,
	0x65, 0x26, 0xa7, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x21, 0x89, 0x08, 0xc9, 0x70, 0x71,
	0x86, 0x16, 0xa7, 0x06, 0x24, 0x16, 0x25, 0xe6, 0x16, 0x4b, 0x30, 0x81, 0xa5, 0x11, 0x02, 0x49,
	0x6c, 0x60, 0x43, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x19, 0xca, 0xf5, 0x19, 0x63, 0x00,
	0x00, 0x00,
}
